name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ndadevdev
          outputs: |
            dist/snake.svg?color_snake=#38bdf8&color_background=#0d1117&color_dots=#161b22,#0c4a6e,#075985,#0369a1,#0ea5e9

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update snake svg"
          file_pattern: dist/snake.svg
